import { useState } from "react";
import { useGetBills, useCreateBill, useGetProducts, useGetCompanySettings } from "@workspace/api-client-react";
import { Plus, Receipt, Printer, FileText, Trash2, Eye } from "lucide-react";
import { useAuth } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Skeleton } from "@/components/ui/skeleton";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { format } from "date-fns";

export default function Bills() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const isStaff = user?.role === "staff";

  const { data: bills, isLoading, refetch } = useGetBills();
  const { data: products } = useGetProducts();
  const { data: companySettings } = useGetCompanySettings();
  const createMutation = useCreateBill();
  const isPdfLogo = Boolean(companySettings?.logoPath?.toLowerCase().includes(".pdf"));

  const [isFormOpen, setIsFormOpen] = useState(false);
  const [viewBill, setViewBill] = useState<any>(null);

  // Bill creation state
  const [customerName, setCustomerName] = useState("");
  const [customerPhone, setCustomerPhone] = useState("");
  const [customerGst, setCustomerGst] = useState("");
  const [customerAddress, setCustomerAddress] = useState("");
  const [placeOfSupply, setPlaceOfSupply] = useState("");
  const [phoneError, setPhoneError] = useState("");
  const [items, setItems] = useState<Array<{productId: number, quantity: number, unitPrice: number, discount: number, gst: number}>>([]);

  const handlePrint = () => {
    window.print();
  };

  const addItem = () => {
    setItems([...items, { productId: 0, quantity: 1, unitPrice: 0, discount: 0, gst: 18 }]);
  };

  const removeItem = (index: number) => {
    const newItems = [...items];
    newItems.splice(index, 1);
    setItems(newItems);
  };

  const updateItem = (index: number, field: string, value: any) => {
    const newItems = [...items];
    (newItems[index] as any)[field] = value;
    
    if (field === 'productId') {
      const prod = products?.find(p => p.id === parseInt(value));
      if (prod) {
        newItems[index].unitPrice = prod.price;
        newItems[index].gst = prod.gst || 18;
      }
    }
    
    setItems(newItems);
  };

  const calculateTotal = () => {
    return items.reduce((sum, item) => {
      const subtotal = item.quantity * item.unitPrice;
      const afterDiscount = subtotal - (item.discount || 0);
      const tax = afterDiscount * ((item.gst || 0) / 100);
      return sum + afterDiscount + tax;
    }, 0);
  };

  const handlePhoneChange = (val: string) => {
    const digits = val.replace(/\D/g, "").slice(0, 10);
    setCustomerPhone(digits);
    if (digits.length > 0 && digits.length < 10) {
      setPhoneError("Mobile number must be 10 digits");
    } else {
      setPhoneError("");
    }
  };

  const handleCreate = () => {
    if (!customerName || items.length === 0 || items.some(i => !i.productId)) {
      toast.error("Please fill all required fields");
      return;
    }
    if (customerPhone && customerPhone.length !== 10) {
      toast.error("Mobile number must be exactly 10 digits");
      return;
    }

    createMutation.mutate({
      data: {
        customerName,
        customerPhone: customerPhone || undefined,
        customerGst: customerGst || undefined,
        customerAddress: customerAddress || undefined,
        items,
        notes: placeOfSupply ? `Place of Supply: ${placeOfSupply}` : undefined,
      }
    }, {
      onSuccess: (res) => {
        toast.success("Bill generated successfully");
        setIsFormOpen(false);
        refetch();
        setViewBill(res);
      },
      onError: () => toast.error("Failed to generate bill")
    });
  };

  const resetForm = () => {
    setCustomerName("");
    setCustomerPhone("");
    setCustomerGst("");
    setCustomerAddress("");
    setPlaceOfSupply("");
    setPhoneError("");
    setItems([]);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 no-print">
        <div>
          <h2 className="text-2xl font-bold text-white tracking-tight">
            {isAdmin ? "Bill History" : "Bill Generator"}
          </h2>
          {isAdmin && (
            <p className="text-sm text-muted-foreground mt-1">View-only — bills are generated by staff</p>
          )}
        </div>
        {isStaff && (
          <Button onClick={() => { setIsFormOpen(true); resetForm(); }} className="bg-primary text-white">
            <Plus size={16} className="mr-2" /> Generate New Bill
          </Button>
        )}
      </div>

      {/* Bill Print View */}
      {viewBill && (
        <div className="max-w-4xl mx-auto">
          {/* Action bar - hidden on print */}
          <div className="no-print flex justify-between items-center mb-4">
            <h3 className="text-lg font-semibold text-white">Bill Preview</h3>
            <div className="flex gap-3">
               <Button onClick={() => setViewBill(null)} variant="outline" className="border-white/10 hover:bg-white/10 text-white">
                 Close
               </Button>
               <Button onClick={handlePrint} className="bg-blue-600 hover:bg-blue-700 text-white">
                 <Printer className="mr-2" size={16} /> Print Bill
               </Button>
            </div>
          </div>

          {/* White paper invoice */}
          <div
            id="bill-print-area"
            style={{
              background: "#ffffff",
              color: "#333333",
              fontFamily: "sans-serif",
              overflow: "hidden",
              position: "relative"
            }}
            className="print:shadow-none print:w-full print:h-auto bg-white shadow-lg rounded-xl border border-gray-200"
          >
            <div style={{ padding: "32px" }}>
              {/* Header: TAX INVOICE & ORIGINAL FOR RECIPIENT */}
              <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "16px" }}>
                <h2 style={{ color: "#3B82F6", margin: 0, fontSize: "16px", letterSpacing: "2px", fontWeight: "bold" }}>TAX INVOICE</h2>
                <span style={{ fontSize: "12px", fontWeight: 600, color: "#666" }}>ORIGINAL FOR RECIPIENT</span>
              </div>

              {/* Company Info & Logo */}
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "20px" }}>
                <div>
                  <h1 style={{ margin: "0 0 8px 0", fontSize: "24px", fontWeight: "bold", color: "#111", textTransform: "uppercase" }}>
                    {companySettings?.name || "YOUR COMPANY NAME"}
                  </h1>
                  <div style={{ fontSize: "12px", color: "#333", lineHeight: "1.4" }}>
                    {companySettings?.gstin && <p style={{ margin: 0 }}><strong>GSTIN: {companySettings.gstin}</strong> {companySettings?.pan && <span>&nbsp;&nbsp;&nbsp;<strong>PAN: {companySettings.pan}</strong></span>}</p>}
                    <p style={{ margin: "4px 0" }}>{companySettings?.address || "Add company address in settings"}</p>
                    <p style={{ margin: 0 }}>
                      <strong>Mobile</strong> {companySettings?.phoneNumber || "-"} &nbsp;&nbsp;&nbsp;
                      <strong>Email</strong> {companySettings?.email || "-"}
                    </p>
                    {(companySettings?.bankName || companySettings?.accountNumber || companySettings?.ifsc || companySettings?.upiId) && (
                      <div style={{ marginTop: "6px", color: "#333" }}>
                        {companySettings?.bankName && <p style={{ margin: 0 }}><strong>Bank:</strong> {companySettings.bankName}</p>}
                        {companySettings?.accountNumber && <p style={{ margin: 0 }}><strong>Account:</strong> {companySettings.accountNumber}</p>}
                        {companySettings?.ifsc && <p style={{ margin: 0 }}><strong>IFSC:</strong> {companySettings.ifsc}</p>}
                        {companySettings?.upiId && <p style={{ margin: 0 }}><strong>UPI:</strong> {companySettings.upiId}</p>}
                      </div>
                    )}
                  </div>
                </div>
                <div className="space-y-3" style={{ textAlign: "right" }}>
                  {companySettings?.logoPath ? (
                    isPdfLogo ? (
                      <a
                        href={companySettings.logoPath}
                        target="_blank"
                        rel="noreferrer"
                        style={{ display: "inline-block", fontSize: "11px", color: "#3B82F6", textDecoration: "none", border: "1px solid #93c5fd", borderRadius: "6px", padding: "6px 10px", fontWeight: 600 }}
                      >
                        View PDF Logo
                      </a>
                    ) : (
                      <img src={companySettings.logoPath} alt="Logo" style={{ maxHeight: "80px", maxWidth: "160px", objectFit: "contain" }} />
                    )
                  ) : (
                    <div style={{ width: "80px", height: "80px", background: "#f3f4f6", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: "bold", color: "#9ca3af" }}>LOGO</div>
                  )}
                </div>
              </div>

              {/* Invoice details grid */}
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "20px", marginBottom: "20px", fontSize: "12px" }}>
                <div>
                  <p style={{ margin: 0 }}><strong>Invoice #:</strong> {viewBill.billNumber}</p>
                  <div style={{ marginTop: "12px" }}>
                    <p style={{ margin: "0 0 4px 0", color: "#666" }}>Customer Details:</p>
                    <p style={{ margin: 0, fontWeight: "bold" }}>{viewBill.customerName}</p>
                    {viewBill.customerGst && <p style={{ margin: "4px 0 0 0" }}><strong>GSTIN: {viewBill.customerGst}</strong></p>}
                    {viewBill.customerPhone && <p style={{ margin: "4px 0 0 0" }}>Phone: {viewBill.customerPhone}</p>}
                  </div>
                </div>
                <div>
                  <p style={{ margin: 0 }}><strong>Invoice Date:</strong> {viewBill.createdAt ? format(new Date(viewBill.createdAt), 'dd MMM yyyy') : '-'}</p>
                  <div style={{ marginTop: "12px" }}>
                    <p style={{ margin: "0 0 4px 0", color: "#666" }}>Billing Address:</p>
                    <p style={{ margin: 0 }}>{viewBill.customerAddress || "-"}</p>
                  </div>
                </div>
                <div>
                  <p style={{ margin: 0 }}><strong>Due Date:</strong> {viewBill.createdAt ? format(new Date(viewBill.createdAt), 'dd MMM yyyy') : '-'}</p>
                </div>
              </div>

              {/* Place of Supply */}
              <div style={{ marginBottom: "20px", fontSize: "12px" }}>
                <p style={{ margin: 0, color: "#666" }}>Place of Supply:</p>
                <p style={{ margin: 0, fontWeight: "bold" }}>{viewBill.customerAddress || "TAMIL NADU"}</p>
              </div>

              {/* Items table */}
              <table style={{ width: "100%", borderCollapse: "collapse", marginBottom: "8px", fontSize: "11px" }}>
                <thead>
                  <tr>
                    <th style={{ padding: "8px 4px", textAlign: "left", borderTop: "2px solid #3B82F6", borderBottom: "1px solid #3B82F6", color: "#333", width: "4%" }}>#</th>
                    <th style={{ padding: "8px 4px", textAlign: "left", borderTop: "2px solid #3B82F6", borderBottom: "1px solid #3B82F6", color: "#333" }}>Item</th>
                    <th style={{ padding: "8px 4px", textAlign: "right", borderTop: "2px solid #3B82F6", borderBottom: "1px solid #3B82F6", color: "#333" }}>Rate / Item</th>
                    <th style={{ padding: "8px 4px", textAlign: "center", borderTop: "2px solid #3B82F6", borderBottom: "1px solid #3B82F6", color: "#333" }}>Disc (%)</th>
                    <th style={{ padding: "8px 4px", textAlign: "center", borderTop: "2px solid #3B82F6", borderBottom: "1px solid #3B82F6", color: "#333" }}>Qty</th>
                    <th style={{ padding: "8px 4px", textAlign: "right", borderTop: "2px solid #3B82F6", borderBottom: "1px solid #3B82F6", color: "#333" }}>Taxable Value</th>
                    <th style={{ padding: "8px 4px", textAlign: "right", borderTop: "2px solid #3B82F6", borderBottom: "1px solid #3B82F6", color: "#333" }}>Tax Amount</th>
                    <th style={{ padding: "8px 4px", textAlign: "right", borderTop: "2px solid #3B82F6", borderBottom: "1px solid #3B82F6", color: "#333" }}>Amount</th>
                  </tr>
                </thead>
                <tbody>
                  {viewBill.items?.map((item: any, idx: number) => {
                    const taxableVal = item.quantity * item.unitPrice * (1 - item.discount / 100);
                    const taxAmt = taxableVal * (item.gst / 100);
                    return (
                      <tr key={idx} style={{ borderBottom: "1px solid #e5e7eb", background: idx % 2 === 0 ? "#fff" : "#f9fafb" }}>
                        <td style={{ padding: "10px 4px", verticalAlign: "top" }}>{idx + 1}</td>
                        <td style={{ padding: "10px 4px" }}>
                          <p style={{ margin: 0, fontWeight: "bold" }}>{item.productName}</p>
                          <p style={{ margin: "2px 0 0 0", color: "#666", fontSize: "10px" }}>HSN: {item.hsnCode || "-"}</p>
                        </td>
                        <td style={{ padding: "10px 4px", textAlign: "right", verticalAlign: "top", fontWeight: "bold" }}>{Number(item.unitPrice).toFixed(2)}</td>
                        <td style={{ padding: "10px 4px", textAlign: "center", verticalAlign: "top" }}>{item.discount > 0 ? `${item.discount}%` : "-"}</td>
                        <td style={{ padding: "10px 4px", textAlign: "center", verticalAlign: "top" }}>{item.quantity} NOS</td>
                        <td style={{ padding: "10px 4px", textAlign: "right", verticalAlign: "top" }}>{taxableVal.toFixed(2)}</td>
                        <td style={{ padding: "10px 4px", textAlign: "right", verticalAlign: "top" }}>{taxAmt.toFixed(2)} ({item.gst}%)</td>
                        <td style={{ padding: "10px 4px", textAlign: "right", verticalAlign: "top" }}>{Number(item.amount).toFixed(2)}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>

              {/* Totals Section */}
              <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: "8px" }}>
                <table style={{ width: "250px", fontSize: "11px", fontWeight: "bold" }}>
                  <tbody>
                    <tr>
                      <td style={{ padding: "4px 0", textAlign: "right" }}>Taxable Amount</td>
                      <td style={{ padding: "4px 0", textAlign: "right" }}>₹{Number(viewBill.subtotal - viewBill.totalDiscount).toFixed(2)}</td>
                    </tr>
                    <tr>
                      <td style={{ padding: "4px 0", textAlign: "right" }}>CGST {(viewBill.items?.[0]?.gst / 2) || 9}%</td>
                      <td style={{ padding: "4px 0", textAlign: "right" }}>₹{(Number(viewBill.totalGst) / 2).toFixed(2)}</td>
                    </tr>
                    <tr>
                      <td style={{ padding: "4px 0", textAlign: "right" }}>SGST {(viewBill.items?.[0]?.gst / 2) || 9}%</td>
                      <td style={{ padding: "4px 0", textAlign: "right" }}>₹{(Number(viewBill.totalGst) / 2).toFixed(2)}</td>
                    </tr>
                    <tr>
                      <td style={{ padding: "4px 0", textAlign: "right" }}>Round Off</td>
                      <td style={{ padding: "4px 0", textAlign: "right" }}>
                        {((Math.round(Number(viewBill.totalAmount)) - Number(viewBill.totalAmount)) > 0 ? "+" : "") + (Math.round(Number(viewBill.totalAmount)) - Number(viewBill.totalAmount)).toFixed(2)}
                      </td>
                    </tr>
                    <tr>
                      <td style={{ padding: "8px 0", textAlign: "right", fontSize: "14px", fontWeight: "bold" }}>Total</td>
                      <td style={{ padding: "8px 0", textAlign: "right", fontSize: "14px", fontWeight: "bold" }}>₹{Math.round(Number(viewBill.totalAmount)).toFixed(2)}</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              {/* Items / Words Strip */}
              <div style={{ borderTop: "1px solid #3B82F6", borderBottom: "1px solid #3B82F6", padding: "6px 4px", display: "flex", justifyContent: "space-between", fontSize: "10px", color: "#666" }}>
                <div>Total Items / Qty : {viewBill.items?.length} / {viewBill.items?.reduce((s:any, i:any) => s + i.quantity, 0)}</div>
                <div>Total amount (in words): INR {viewBill.amountInWords} Only.</div>
              </div>

              <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: "30px" }}>
                <table style={{ width: "250px", fontSize: "11px", fontWeight: "bold" }}>
                  <tbody>
                    <tr>
                      <td style={{ padding: "4px 0", textAlign: "right", borderBottom: "1px solid #e5e7eb" }}>Amount Payable:</td>
                      <td style={{ padding: "4px 0", textAlign: "right", borderBottom: "1px solid #e5e7eb" }}>₹{Math.round(Number(viewBill.totalAmount)).toFixed(2)}</td>
                    </tr>
                    <tr>
                      <td style={{ padding: "4px 0", textAlign: "right" }}>Total Amount due:</td>
                      <td style={{ padding: "4px 0", textAlign: "right" }}>₹{Math.round(Number(viewBill.totalAmount)).toFixed(2)}</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              {/* Footer details: Bank, QR, Signature */}
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "20px", fontSize: "11px" }}>
                {/* QR Code */}
                <div>
                  <p style={{ margin: "0 0 8px 0", fontWeight: "bold" }}>Pay using UPI:</p>
                  {companySettings?.qrCodePath ? (
                    // Admin uploaded their own QR image — show it directly via vite proxy
                    <img
                      src={companySettings.qrCodePath}
                      alt="UPI QR Code"
                      style={{ width: "100px", height: "100px", objectFit: "contain", border: "1px solid #e5e7eb", padding: "4px" }}
                    />
                  ) : companySettings?.upiId ? (
                    // No uploaded QR — generate one from admin's real UPI ID
                    <div style={{ width: "100px", height: "100px", border: "1px solid #e5e7eb", padding: "4px", background: `url('https://api.qrserver.com/v1/create-qr-code/?size=100x100&data=${encodeURIComponent(`upi://pay?pa=${companySettings.upiId}&pn=${companySettings?.name || ""}&am=${Math.round(Number(viewBill.totalAmount))}`)}&bgcolor=ffffff&color=000000&qzone=1') center/contain no-repeat` }} />
                  ) : (
                    <div style={{ width: "100px", height: "100px", border: "1px dashed #e5e7eb", display: "flex", alignItems: "center", justifyContent: "center", color: "#9ca3af", fontSize: "10px", textAlign: "center", padding: "8px" }}>
                      Set UPI ID in Settings
                    </div>
                  )}
                  {companySettings?.upiId && (
                    <p style={{ margin: "4px 0 0 0", fontSize: "10px", color: "#666" }}>{companySettings.upiId}</p>
                  )}
                </div>
                
                {/* Bank Details from company settings */}
                <div>
                  <p style={{ margin: "0 0 8px 0", fontWeight: "bold" }}>Bank Details:</p>
                  <div style={{ display: "grid", gridTemplateColumns: "80px 1fr", gap: "4px", color: "#333" }}>
                    {companySettings?.bankName && (<><span>Bank:</span> <strong>{companySettings.bankName}</strong></>)}
                    {companySettings?.accountNumber && (<><span>Account #:</span> <strong>{companySettings.accountNumber}</strong></>)}
                    {companySettings?.ifsc && (<><span>IFSC Code:</span> <strong>{companySettings.ifsc}</strong></>)}
                  </div>
                </div>

                {/* Signature */}
                <div style={{ textAlign: "right", display: "flex", flexDirection: "column", justifyContent: "space-between" }}>
                  <p style={{ margin: 0, color: "#666" }}>For {companySettings?.name || "DHASVIN ENTERPRISES"}</p>
                  <div style={{ height: "60px", display: "flex", alignItems: "center", justifyContent: "flex-end" }}>
                    <span style={{ fontFamily: "'Brush Script MT', cursive", fontSize: "24px" }}>
                      {companySettings?.name ? companySettings.name.split(" ").slice(0, 2).join(" ") : "Authorized"}
                    </span>
                  </div>
                  <p style={{ margin: 0, color: "#666" }}>Authorized Signatory</p>
                </div>
              </div>

            </div>
          </div>
        </div>
      )}

      {/* Bill List */}
      {!viewBill && (
        <>
          {isLoading ? (
            <div className="glass-panel p-6 rounded-xl">
              <Skeleton className="h-[400px] w-full" />
            </div>
          ) : bills?.length === 0 ? (
            <div className="glass-panel p-12 rounded-xl flex flex-col items-center justify-center text-center">
              <Receipt className="h-16 w-16 text-muted-foreground mb-4 opacity-50" />
              <h3 className="text-xl font-bold text-white mb-2">No bills generated</h3>
              <p className="text-muted-foreground">Click "Generate New Bill" to create your first invoice.</p>
            </div>
          ) : (
            <div className="glass-panel rounded-xl border border-white/5 overflow-hidden">
              <div className="overflow-x-auto">
                <table className="w-full text-sm text-left">
                  <thead className="text-xs text-muted-foreground uppercase bg-white/5 border-b border-white/5">
                    <tr>
                      <th className="px-6 py-4">Bill No</th>
                      <th className="px-6 py-4">Date</th>
                      <th className="px-6 py-4">Customer</th>
                      <th className="px-6 py-4 text-right">Amount</th>
                      <th className="px-6 py-4 text-center">Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-white/5">
                    {bills?.map(bill => (
                      <tr key={bill.id} className="hover:bg-white/5 transition-colors">
                        <td className="px-6 py-4 font-mono font-medium text-primary">{bill.billNumber}</td>
                        <td className="px-6 py-4 text-muted-foreground">
                          {bill.createdAt ? format(new Date(bill.createdAt), 'MMM dd, yyyy HH:mm') : '-'}
                        </td>
                        <td className="px-6 py-4 text-white">{bill.customerName}</td>
                        <td className="px-6 py-4 text-right font-mono font-bold text-white">₹{bill.totalAmount}</td>
                        <td className="px-6 py-4 text-center">
                          <Button size="sm" variant="outline" className="h-8 border-white/10 hover:bg-white/10" onClick={() => setViewBill(bill)}>
                            <Eye size={14} className="mr-2" /> {isAdmin ? "View" : "Open"}
                          </Button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </>
      )}

      {/* Create Bill Modal */}
      <Dialog open={isFormOpen} onOpenChange={setIsFormOpen}>
        <DialogContent className="bg-card border-white/10 text-white sm:max-w-[700px] max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Generate New Bill</DialogTitle>
          </DialogHeader>
          <div className="space-y-6 pt-4">
            <div className="rounded-3xl border border-border bg-card/90 p-6 shadow-[0_25px_80px_-40px_rgba(0,0,0,0.12)]">
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-6">
                <div>
                  <h3 className="text-lg font-semibold text-foreground">Customer & Billing Details</h3>
                  <p className="text-sm text-muted-foreground mt-1">Capture GSTIN, mobile, billing address and supply information before generating the bill.</p>
                </div>
                <span className="inline-flex items-center rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">Staff billing</span>
              </div>

              <div className="grid gap-4 lg:grid-cols-2">
                <div>
                  <label className="text-sm font-medium mb-1 block text-white">Customer Name*</label>
                  <Input value={customerName} onChange={e => setCustomerName(e.target.value)} className="bg-white/5 border-white/10 text-white placeholder:text-muted-foreground" placeholder="Enter customer name" />
                </div>
                <div>
                  <label className="text-sm font-medium mb-1 block text-white">Mobile Number</label>
                  <Input
                    type="tel"
                    inputMode="numeric"
                    placeholder="10-digit mobile number"
                    value={customerPhone}
                    onChange={e => handlePhoneChange(e.target.value)}
                    maxLength={10}
                    className={`bg-white/5 border-white/10 text-white placeholder:text-muted-foreground ${phoneError ? "border-red-500" : ""}`}
                  />
                  {phoneError && (
                    <p className="text-xs text-red-400 mt-1">{phoneError}</p>
                  )}
                  {customerPhone.length === 10 && !phoneError && (
                    <p className="text-xs text-emerald-400 mt-1">✓ Valid mobile number</p>
                  )}
                </div>
                <div>
                  <label className="text-sm font-medium mb-1 block text-white">Customer GSTIN</label>
                  <Input value={customerGst} onChange={e => setCustomerGst(e.target.value)} placeholder="GSTIN (optional)" className="bg-white/5 border-white/10 text-white placeholder:text-muted-foreground" />
                </div>
                <div>
                  <label className="text-sm font-medium mb-1 block text-white">Place of Supply</label>
                  <Input value={placeOfSupply} onChange={e => setPlaceOfSupply(e.target.value)} placeholder="State / Union Territory" className="bg-white/5 border-white/10 text-white placeholder:text-muted-foreground" />
                </div>
              </div>

              <div className="mt-4">
                <label className="text-sm font-medium mb-2 block text-white">Billing Address</label>
                <Textarea
                  value={customerAddress}
                  onChange={e => setCustomerAddress(e.target.value)}
                  placeholder="Enter full billing address"
                  className="min-h-[100px] bg-white/5 border-white/10 text-white placeholder:text-muted-foreground"
                />
              </div>
            </div>

            <div className="space-y-4">
              <div className="flex justify-between items-center">
                <h4 className="font-semibold">Items</h4>
                <Button size="sm" variant="outline" onClick={addItem} className="border-white/10 hover:bg-white/5">
                  <Plus size={14} className="mr-1" /> Add Row
                </Button>
              </div>

              {items.map((item, idx) => (
                <div key={idx} className="flex gap-2 items-end bg-white/5 p-3 rounded-lg border border-white/5">
                  <div className="flex-1">
                    <label className="text-xs text-muted-foreground mb-1 block">Product</label>
                    <select 
                      className="w-full h-9 rounded-md bg-black/40 border border-white/10 text-sm px-2 text-white outline-none focus:ring-1 focus:ring-primary"
                      value={item.productId || ""}
                      onChange={(e) => updateItem(idx, 'productId', e.target.value)}
                    >
                      <option value="" disabled>Select product...</option>
                      {products?.map(p => <option key={p.id} value={p.id}>{p.name} (₹{p.price})</option>)}
                    </select>
                  </div>
                  <div className="w-20">
                    <label className="text-xs text-muted-foreground mb-1 block">Qty</label>
                    <Input type="number" min="1" value={item.quantity} onChange={(e) => updateItem(idx, 'quantity', parseInt(e.target.value))} className="h-9 bg-black/40 border-white/10" />
                  </div>
                  <div className="w-24">
                    <label className="text-xs text-muted-foreground mb-1 block">Price</label>
                    <Input type="number" value={item.unitPrice} onChange={(e) => updateItem(idx, 'unitPrice', parseFloat(e.target.value))} className="h-9 bg-black/40 border-white/10" />
                  </div>
                  <Button variant="ghost" size="icon" onClick={() => removeItem(idx)} className="h-9 w-9 text-red-400 hover:text-red-300 hover:bg-red-400/10">
                    <Trash2 size={16} />
                  </Button>
                </div>
              ))}
            </div>

            {items.length > 0 && (
              <div className="flex justify-end pt-4 border-t border-white/10">
                <div className="text-right">
                  <p className="text-sm text-muted-foreground">Estimated Total</p>
                  <p className="text-2xl font-bold text-primary">₹{calculateTotal().toFixed(2)}</p>
                </div>
              </div>
            )}

            <div className="flex justify-end gap-3 pt-2">
              <Button variant="outline" onClick={() => setIsFormOpen(false)} className="bg-transparent border-white/10 hover:bg-white/5">Cancel</Button>
              <Button onClick={handleCreate} disabled={createMutation.isPending} className="bg-primary text-white">
                {createMutation.isPending ? "Generating..." : "Generate Bill"}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
